# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "loK4k3IcMow1DsIv+/ixJnz9EuNRbeVgjx4pojfhedH/WRI4OZZzdhwoKjRWSNXatg2dir7ecGNAZXNDZbJl+Jl7pud/SA+DgJEwQnkd2t0tNhhUFVCtHGHF1b2/9x/Sce3piXV6tINw3RIRxh1bNEeFHfcFEoAGBlyeJdDfvjnTDWsWo6zvbWx0ZFyni3+6gGzVaese67BjgqIA8ux/IMyVBzdg5EFu0BbdonVglEfYIzHmszgBzmW8OOvdmSVucS8R/cNUw6c5u35TIY5mW5eYqkaDCqd4Yi0qd756bz6Doh9hFRw7478LF0vfSVRkfrbgrQBA7GasPEJbL7pEFsUok3rP9+nOTLUwQLmTiBd/MtrSRiQzOnu1/sfwha2d5sFMkXMVbvhCDtk7oE9TwHdfD/oYk+hpesqCRA8SzKozUrRpwg1GqvPsSXxOHoS2S+4/xuUtWbZeicKncz+3gmGk5ebUP8/Suhi7X0yyq8/8YcqflPm+bLCByUXX0dIEmPmZT7oemTN9iH69q8SGg+KzM/j16oiqeCbPUERG8w1jZql1zAPGvswbCPQzZfRATUw+Fq1iDUKrndTE3Rf4cEd7IRKsGPf8APnW9zv5rMXMYQ6nIzjQBWElNvzK+aVzlfaAQfQZJ+Gl/nNXw68eH/oZ2piYVYwI9jIf57eAtgE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
