travis:
  secure:
    BINSTAR_TOKEN: loK4k3IcMow1DsIv+/ixJnz9EuNRbeVgjx4pojfhedH/WRI4OZZzdhwoKjRWSNXatg2dir7ecGNAZXNDZbJl+Jl7pud/SA+DgJEwQnkd2t0tNhhUFVCtHGHF1b2/9x/Sce3piXV6tINw3RIRxh1bNEeFHfcFEoAGBlyeJdDfvjnTDWsWo6zvbWx0ZFyni3+6gGzVaese67BjgqIA8ux/IMyVBzdg5EFu0BbdonVglEfYIzHmszgBzmW8OOvdmSVucS8R/cNUw6c5u35TIY5mW5eYqkaDCqd4Yi0qd756bz6Doh9hFRw7478LF0vfSVRkfrbgrQBA7GasPEJbL7pEFsUok3rP9+nOTLUwQLmTiBd/MtrSRiQzOnu1/sfwha2d5sFMkXMVbvhCDtk7oE9TwHdfD/oYk+hpesqCRA8SzKozUrRpwg1GqvPsSXxOHoS2S+4/xuUtWbZeicKncz+3gmGk5ebUP8/Suhi7X0yyq8/8YcqflPm+bLCByUXX0dIEmPmZT7oemTN9iH69q8SGg+KzM/j16oiqeCbPUERG8w1jZql1zAPGvswbCPQzZfRATUw+Fq1iDUKrndTE3Rf4cEd7IRKsGPf8APnW9zv5rMXMYQ6nIzjQBWElNvzK+aVzlfaAQfQZJ+Gl/nNXw68eH/oZ2piYVYwI9jIf57eAtgE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
